- hosts: "{{ ansible_play_batch }}" 
  serial: 1
  become: false
  environment:
    PATH: /opt/mqm/bin:{{ ansible_env.PATH }}

  roles: 
    - role: setupusers
      vars:
        gid: 909
    - downloadmq
    - installmq
