---

- name: Create mqm group
  group:
    name: mqm
    gid: "{{ mqmGid }}"

- name: Create mqm user
  user:
    name: mqm
    uid: "{{ mqmUid }}"
    group: mqm

- name: Create an admin user
  user:
    name: mqadm
    groups: mqm
    append: yes

- name: Add 'mqclient' group
  become: true
  group:
    name: mqclient
    state: present
    gid: "{{ appGid }}"

- name: Add the user 'app' with a specific UID
  become: true
  vars:
    apppassword: "Passw0rd"
  user:
    name: app
    password: "{{ 'apppassword' | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
    uid: "{{ appUid }}"
    group: mqclient



